### ISSUE TITLE
Use the Backup System

### ISSUE THREAD

**Issue by MaeveKyalwann** [DavidBrightSparc/Tenets-of-IT#6]
If you have a primary system that is malfunctioning, threaten the system by starting to set up the backup system.  Usually, by the time the backup is 90% ready....the primary will magically start working again.

**Comment by majorlinux** [comment]
I've really had that happen to me with a personal system and two capture cards.

To this day, I have an AverMedia card installed to make sure my Elgato card doesn't give me trouble.

**Comment by DavidBrightSparc** [comment]
Added. Thank you for your contribution.
